import {makeHtmlElementConstructor} from './dom-component-types'

export const H1 = makeHtmlElementConstructor('h1')
export const H2 = makeHtmlElementConstructor('h2')
export const H3 = makeHtmlElementConstructor('h3')
export const Div = makeHtmlElementConstructor('div')
export const Header = makeHtmlElementConstructor('header')
export const Footer = makeHtmlElementConstructor('footer')
export const Span = makeHtmlElementConstructor('span')
export const A = makeHtmlElementConstructor('a')
export const P = makeHtmlElementConstructor('p')
export const B = makeHtmlElementConstructor('b')
export const Br = makeHtmlElementConstructor('br')
export const Img = makeHtmlElementConstructor('img')
export const Ul = makeHtmlElementConstructor('ul')
export const Li = makeHtmlElementConstructor('li')
export const Ol = makeHtmlElementConstructor('ol')
export const Video = makeHtmlElementConstructor('video')
export const Source = makeHtmlElementConstructor('source')
export const Idiomatic = makeHtmlElementConstructor('i')
export const Button = makeHtmlElementConstructor('button')
export const Canvas = makeHtmlElementConstructor('canvas')
export const Form = makeHtmlElementConstructor('form')
export const Input = makeHtmlElementConstructor('input')
export const DataList = makeHtmlElementConstructor('datalist')
export const Option = makeHtmlElementConstructor('option')
export const Textarea = makeHtmlElementConstructor('textarea')
export const Label = makeHtmlElementConstructor('label')

export const Table = makeHtmlElementConstructor('table')
export const Tr = makeHtmlElementConstructor('tr')
export const Td = makeHtmlElementConstructor('td')
export const Th = makeHtmlElementConstructor('th')
