import {makeHtmlElementConstructor} from './host-component-types'

export const H1 = makeHtmlElementConstructor('h1')
export const H2 = makeHtmlElementConstructor('h2')
export const H3 = makeHtmlElementConstructor('h3')
export const Div = makeHtmlElementConstructor('div')
export const Header = makeHtmlElementConstructor('header')
export const footer = makeHtmlElementConstructor('footer')
export const span = makeHtmlElementConstructor('span')
export const a = makeHtmlElementConstructor('a')
export const p = makeHtmlElementConstructor('p')
export const b = makeHtmlElementConstructor('b')
export const br = makeHtmlElementConstructor('br')
export const img = makeHtmlElementConstructor('img')
export const ul = makeHtmlElementConstructor('ul')
export const li = makeHtmlElementConstructor('li')
export const ol = makeHtmlElementConstructor('ol')
export const video = makeHtmlElementConstructor('video')
export const source = makeHtmlElementConstructor('source')
export const idiomatic = makeHtmlElementConstructor('i')
export const Button = makeHtmlElementConstructor('button')
export const canvas = makeHtmlElementConstructor('canvas')
export const form = makeHtmlElementConstructor('form')
export const input = makeHtmlElementConstructor('input')
export const textarea = makeHtmlElementConstructor('textarea')
export const label = makeHtmlElementConstructor('label')

export const table = makeHtmlElementConstructor('table')
export const tr = makeHtmlElementConstructor('tr')
export const td = makeHtmlElementConstructor('td')
export const th = makeHtmlElementConstructor('th')
